language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
before_script:
  - composer install --no-interaction
  - test $(phpenv version-name) != 5.3 && composer require --dev --no-interaction 'cebe/markdown:*' 'kzykhys/ciconia:*'
