dist: xenial
language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
before_script:
  - composer install --no-interaction
